import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import FacebookSessionButton from "../context/Facebook/components/FacebookSessionButton";
import InstagramStoriesButton from "../context/Facebook/components/InstagramStoriesButton";
import Stories from "../context/Facebook/components/Stories";
const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <br />
        <FacebookSessionButton />
        <br />
        <br />
        <br />
        <InstagramStoriesButton />
        <br />
        <Stories />
      </main>
      <footer></footer>
    </div>
  );
};

export default Home;
